---
# tasks file for awswebserver
- name: install httpd
  package:
          name: httpd
          state: present
  become: yes

- name: start httpd service
  service:
          name: httpd
          state: started
  become: yes

- name: copy webpages to deploy
  template:
          src: index.html
          dest: /var/www/html
  become: yes

